language: minimal

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

services:
  - docker

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

before_script:
  # make sure git tests do not complain about user/email not being set
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

jobs:
  include:
    - stage: test
      script: docker run --rm -v $PWD:/home/dandelion/app -w /home/dandelion/app --user=root dandelionphp/php:7.4-cli-alpine-dev /bin/sh -c "make test"
    - stage: bundle
      script: docker run --rm -v $PWD:/home/dandelion/app -w /home/dandelion/app --user=root dandelionphp/php:7.4-cli-alpine-dev /bin/sh -c "make bundle"
    - stage: build
      script: make docker-build

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: bin/dandelion.phar
    skip_cleanup: true
    on:
      tags: true
      repo: dandelionphp/dandelion
  - provider: script
    script: make docker-push
    on:
      tags: true
