language: minimal

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

services:
  - docker

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

before_script:
  # make sure git tests do not complain about user/email not being set
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

jobs:
  include:
    - stage: test
      script: docker run -it --rm -v $PWD:/tmp -w /tmp dandelionphp/php:7.4-cli-alpine-dev -c make test
    - stage: bundle
      script: docker run -it --rm -v $PWD:/tmp -w="/tmp" dandelionphp/php:7.4-cli-alpine-dev -c make bundle
    - stage: build
      script: 
        - docker build -t . dandelion
        - docker tag dandelion dandelionphp/dandelion:${TRAVIS_TAG}
        - docker tag dandelion dandelionphp/dandelion:latest
      if: tag =~ ^\d+\.\d+\.\d+$

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: bin/dandelion.phar
    skip_cleanup: true
    on:
      tags: true
      repo: dandelionphp/dandelion
  - provider: script
    script: bash scripts/docker.sh
    on: 
      tags: true
